### ISSUE TITLE
The code block on the right side exceeds the normal display range of rendering.

### ISSUE THREAD

**Issue by murenren1** [transitive-bullshit/nextjs-notion-starter-kit#544]
#### Description

The code block on the right side exceeds the normal display range of rendering.-->
<img width="1252" alt="截屏2023-09-05 17 04 31" src="https://github.com/transitive-bullshit/nextjs-notion-starter-kit/assets/59929648/d1acc08a-27eb-4754-af95-995ce235a88c">

#### Notion Test Page ID
https://hyhai.notion.site/Notion-StartupAI-2023-09-04-Notion-OpenAI-2e84d630f7a94d349841f75b80d29aaf?pvs=4

**Comment by murenren1** [comment]
Got it.

**Comment by ChiaYuSu** [comment]
You can add css to prevent this situation
```css
ol:not(:has(> li)),
ul:not(:has(> li)) {
    padding: 0 !important;
}
```

**Comment by 0chil** [comment]
You can add the css below if the issue occurs for images under list.
Not tested whether it is also effective for code blocks or not. (I think it will)

- CSS
  ```css
  .notion-list {
    max-width: 100%;
  }
  ```

- Before
  <img width="327" alt="image" src="https://github.com/transitive-bullshit/nextjs-notion-starter-kit/assets/39221443/53765ec5-81f6-4cd1-9a11-6630245b7cb2">

- After
  <img width="328" alt="image" src="https://github.com/transitive-bullshit/nextjs-notion-starter-kit/assets/39221443/76fb106c-e55d-4fcc-a82e-159002b55750">
